Script change.

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -55,14 +55,13 @@ jobs:
 
       # Check if log contains any INVALID items
       - name: Check for invalid items
-        continue-on-error: true
         run: |
           echo -n "Number of invalid files: "
           set +e
           grep -c "^ INVALID:" logs/validate.log
-          set -e
-          if $? ; then
-            echo "FAILURE found: $?"
-          else
+          if [ `grep -c "^ INVALID:" logs/validate.log` -eq 0 ]; then
             echo "No FAILURE found: $?"
+          else
+            echo "FAILURE found: $?"
           fi
+          set -e
