Script change.

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -59,4 +59,4 @@ jobs:
           echo -n "Number of invalid files: "
           grep -c "^ INVALID:" logs/validate.log
           grep -q "^ INVALID:" logs/validate.log
-          if [ $? -eq 0 ]; then echo "No FAILURE found: $?"; exit 1; else echo "FAILURE found: $?"; exit 0; fi
+          if [ $? -eq 0 ]; then echo "No FAILURE found: $?"; else echo "FAILURE found: $?"; fi
